# Network:
#     ChannelsNum: 3
#     ClassesNum: 5

# Classes:


# Trainer:
#     BatchSize: 5
#     LearningRate: 0.01
#     Scale: 0.5   # Downscaling factor of the images
#     ValidationRatio: 0.1
#     AMP: True    # Use mixed precision

# Dataset:
#     TrainDir: "/home/avent/Desktop/generated_data/2026-02-02-131248"
#     ValidationRatio: 0.1

Network:
    ChannelsNum: 3
    ClassesNum: 5
    Bilinear: False   # Use bilinear upsampling

Trainer:
    LearningRate: 2.0e-3
    Scale: 0.5   # Downscaling factor of the images
    AMP: True    # Use mixed precision
    SaveONNX: False

Dataset:
    TrainDir: "/home/avent/Desktop/generated_data/2026-02-02-131248"
    # TestDir: "/home/avent/Desktop/PythonProjects/Image-Segmentation/Template-MNIST/data/dataset/test"
    BatchSize: 5
    ValidationRatio: 0.1