Network:
    ChannelsNum: 3
    ClassesNum: 10
    Bilinear: False   # Use bilinear upsampling

Trainer:
    LearningRate: 1.0e-3
    Scale: 0.5   # Downscaling factor of the images
    AMP: True    # Use mixed precision
    SaveONNX: False

Dataset:
    TrainDir: "/home/avent/Desktop/PythonProjects/Image-Segmentation/Template-MNIST/data/dataset/train"
    TestDir: "/home/avent/Desktop/PythonProjects/Image-Segmentation/Template-MNIST/data/dataset/test"
    BatchSize: 100
    ValidationRatio: 0.1